/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiObject : Base type for most resource objects. It defines the common `type` element that identifies an object's type. It also identifies the element as Swagger's `discriminator`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ApiObject {
    #[serde(rename="GPG_account_key")]
    ApiGpgAccountKey {
    },
    #[serde(rename="account")]
    ApiAccount {
    },
    #[serde(rename="app_user")]
    ApiAppUser {
    },
    #[serde(rename="author")]
    ApiAuthor {
    },
    #[serde(rename="base_commit")]
    ApiBaseCommit {
    },
    #[serde(rename="branching_model")]
    ApiBranchingModel {
    },
    #[serde(rename="branching_model_settings")]
    ApiBranchingModelSettings {
    },
    #[serde(rename="branchrestriction")]
    ApiBranchrestriction {
    },
    #[serde(rename="comment")]
    ApiComment {
    },
    #[serde(rename="commit")]
    ApiCommit {
    },
    #[serde(rename="commit_comment")]
    ApiCommitComment {
    },
    #[serde(rename="commitstatus")]
    ApiCommitstatus {
    },
    #[serde(rename="committer")]
    ApiCommitter {
    },
    #[serde(rename="component")]
    ApiComponent {
    },
    #[serde(rename="deploy_key")]
    ApiDeployKey {
    },
    #[serde(rename="deployment")]
    ApiDeployment {
    },
    #[serde(rename="deployment_environment")]
    ApiDeploymentEnvironment {
    },
    #[serde(rename="deployment_release")]
    ApiDeploymentRelease {
    },
    #[serde(rename="deployment_state")]
    ApiDeploymentState {
    },
    #[serde(rename="deployment_state_completed")]
    ApiDeploymentStateCompleted {
    },
    #[serde(rename="deployment_state_completed_status")]
    ApiDeploymentStateCompletedStatus {
    },
    #[serde(rename="deployment_state_completed_status_failed")]
    ApiDeploymentStateCompletedStatusFailed {
    },
    #[serde(rename="deployment_state_completed_status_stopped")]
    ApiDeploymentStateCompletedStatusStopped {
    },
    #[serde(rename="deployment_state_completed_status_successful")]
    ApiDeploymentStateCompletedStatusSuccessful {
    },
    #[serde(rename="deployment_state_in_progress")]
    ApiDeploymentStateInProgress {
    },
    #[serde(rename="deployment_state_undeployed")]
    ApiDeploymentStateUndeployed {
    },
    #[serde(rename="deployment_variable")]
    ApiDeploymentVariable {
    },
    #[serde(rename="effective_repo_branching_model")]
    ApiEffectiveRepoBranchingModel {
    },
    #[serde(rename="group")]
    ApiGroup {
    },
    #[serde(rename="issue")]
    ApiIssue {
    },
    #[serde(rename="issue_attachment")]
    ApiIssueAttachment {
    },
    #[serde(rename="issue_comment")]
    ApiIssueComment {
    },
    #[serde(rename="milestone")]
    ApiMilestone {
    },
    #[serde(rename="participant")]
    ApiParticipant {
    },
    #[serde(rename="pipeline")]
    ApiPipeline {
    },
    #[serde(rename="pipeline_build_number")]
    ApiPipelineBuildNumber {
    },
    #[serde(rename="pipeline_cache")]
    ApiPipelineCache {
    },
    #[serde(rename="pipeline_commit_target")]
    ApiPipelineCommitTarget {
    },
    #[serde(rename="pipeline_error")]
    ApiPipelineError {
    },
    #[serde(rename="pipeline_known_host")]
    ApiPipelineKnownHost {
    },
    #[serde(rename="pipeline_ref_target")]
    ApiPipelineRefTarget {
    },
    #[serde(rename="pipeline_schedule")]
    ApiPipelineSchedule {
    },
    #[serde(rename="pipeline_schedule_execution")]
    ApiPipelineScheduleExecution {
    },
    #[serde(rename="pipeline_schedule_execution_errored")]
    ApiPipelineScheduleExecutionErrored {
    },
    #[serde(rename="pipeline_schedule_execution_executed")]
    ApiPipelineScheduleExecutionExecuted {
    },
    #[serde(rename="pipeline_schedule_post_request_body")]
    ApiPipelineSchedulePostRequestBody {
    },
    #[serde(rename="pipeline_schedule_put_request_body")]
    ApiPipelineSchedulePutRequestBody {
    },
    #[serde(rename="pipeline_selector")]
    ApiPipelineSelector {
    },
    #[serde(rename="pipeline_ssh_key_pair")]
    ApiPipelineSshKeyPair {
    },
    #[serde(rename="pipeline_ssh_public_key")]
    ApiPipelineSshPublicKey {
    },
    #[serde(rename="pipeline_state")]
    ApiPipelineState {
    },
    #[serde(rename="pipeline_state_completed")]
    ApiPipelineStateCompleted {
    },
    #[serde(rename="pipeline_state_completed_error")]
    ApiPipelineStateCompletedError {
    },
    #[serde(rename="pipeline_state_completed_expired")]
    ApiPipelineStateCompletedExpired {
    },
    #[serde(rename="pipeline_state_completed_failed")]
    ApiPipelineStateCompletedFailed {
    },
    #[serde(rename="pipeline_state_completed_result")]
    ApiPipelineStateCompletedResult {
    },
    #[serde(rename="pipeline_state_completed_stopped")]
    ApiPipelineStateCompletedStopped {
    },
    #[serde(rename="pipeline_state_completed_successful")]
    ApiPipelineStateCompletedSuccessful {
    },
    #[serde(rename="pipeline_state_in_progress")]
    ApiPipelineStateInProgress {
    },
    #[serde(rename="pipeline_state_in_progress_paused")]
    ApiPipelineStateInProgressPaused {
    },
    #[serde(rename="pipeline_state_in_progress_running")]
    ApiPipelineStateInProgressRunning {
    },
    #[serde(rename="pipeline_state_in_progress_stage")]
    ApiPipelineStateInProgressStage {
    },
    #[serde(rename="pipeline_state_pending")]
    ApiPipelineStatePending {
    },
    #[serde(rename="pipeline_step")]
    ApiPipelineStep {
    },
    #[serde(rename="pipeline_step_error")]
    ApiPipelineStepError {
    },
    #[serde(rename="pipeline_step_state")]
    ApiPipelineStepState {
    },
    #[serde(rename="pipeline_step_state_completed")]
    ApiPipelineStepStateCompleted {
    },
    #[serde(rename="pipeline_step_state_completed_error")]
    ApiPipelineStepStateCompletedError {
    },
    #[serde(rename="pipeline_step_state_completed_expired")]
    ApiPipelineStepStateCompletedExpired {
    },
    #[serde(rename="pipeline_step_state_completed_failed")]
    ApiPipelineStepStateCompletedFailed {
    },
    #[serde(rename="pipeline_step_state_completed_not_run")]
    ApiPipelineStepStateCompletedNotRun {
    },
    #[serde(rename="pipeline_step_state_completed_result")]
    ApiPipelineStepStateCompletedResult {
    },
    #[serde(rename="pipeline_step_state_completed_stopped")]
    ApiPipelineStepStateCompletedStopped {
    },
    #[serde(rename="pipeline_step_state_completed_successful")]
    ApiPipelineStepStateCompletedSuccessful {
    },
    #[serde(rename="pipeline_step_state_in_progress")]
    ApiPipelineStepStateInProgress {
    },
    #[serde(rename="pipeline_step_state_pending")]
    ApiPipelineStepStatePending {
    },
    #[serde(rename="pipeline_step_state_ready")]
    ApiPipelineStepStateReady {
    },
    #[serde(rename="pipeline_target")]
    ApiPipelineTarget {
    },
    #[serde(rename="pipeline_trigger")]
    ApiPipelineTrigger {
    },
    #[serde(rename="pipeline_trigger_manual")]
    ApiPipelineTriggerManual {
    },
    #[serde(rename="pipeline_trigger_push")]
    ApiPipelineTriggerPush {
    },
    #[serde(rename="pipeline_variable")]
    ApiPipelineVariable {
    },
    #[serde(rename="pipelines_config")]
    ApiPipelinesConfig {
    },
    #[serde(rename="pipelines_links_section_href")]
    ApiPipelinesLinksSectionHref {
    },
    #[serde(rename="pipelines_pipeline_links")]
    ApiPipelinesPipelineLinks {
    },
    #[serde(rename="project")]
    ApiProject {
    },
    #[serde(rename="project_branching_model")]
    ApiProjectBranchingModel {
    },
    #[serde(rename="project_deploy_key")]
    ApiProjectDeployKey {
    },
    #[serde(rename="pullrequest")]
    ApiPullrequest {
    },
    #[serde(rename="pullrequest_comment")]
    ApiPullrequestComment {
    },
    #[serde(rename="report")]
    ApiReport {
    },
    #[serde(rename="report_annotation")]
    ApiReportAnnotation {
    },
    #[serde(rename="repository")]
    ApiRepository {
    },
    #[serde(rename="snippet")]
    ApiSnippet {
    },
    #[serde(rename="snippet_comment")]
    ApiSnippetComment {
    },
    #[serde(rename="snippet_commit")]
    ApiSnippetCommit {
    },
    #[serde(rename="ssh_account_key")]
    ApiSshAccountKey {
    },
    #[serde(rename="ssh_key")]
    ApiSshKey {
    },
    #[serde(rename="team")]
    ApiTeam {
    },
    #[serde(rename="user")]
    ApiUser {
    },
    #[serde(rename="version")]
    ApiVersion {
    },
    #[serde(rename="webhook_subscription")]
    ApiWebhookSubscription {
    },
    #[serde(rename="workspace")]
    ApiWorkspace {
    },
    #[serde(rename="workspace_access")]
    ApiWorkspaceAccess {
    },
    #[serde(rename="workspace_base")]
    ApiWorkspaceBase {
    },
    #[serde(rename="workspace_membership")]
    ApiWorkspaceMembership {
    },
}

impl Default for ApiObject {
    fn default() -> Self {
        Self::ApiGpgAccountKey {
        }
        
    }
}


