/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPipelineSshKeyPair {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The SSH private key. This value will be empty when retrieving the SSH key pair.
    #[serde(rename = "private_key", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
    /// The SSH public key.
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
}

impl ApiPipelineSshKeyPair {
    pub fn new(r#type: String) -> ApiPipelineSshKeyPair {
        ApiPipelineSshKeyPair {
            r#type,
            private_key: None,
            public_key: None,
        }
    }
}

