/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTeamLinks {
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Box<models::ApiLink>>,
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::ApiLink>>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<Box<models::ApiLink>>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Box<models::ApiLink>>,
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Box<models::ApiLink>>,
    #[serde(rename = "repositories", skip_serializing_if = "Option::is_none")]
    pub repositories: Option<Box<models::ApiLink>>,
}

impl ApiTeamLinks {
    pub fn new() -> ApiTeamLinks {
        ApiTeamLinks {
            avatar: None,
            param_self: None,
            html: None,
            members: None,
            projects: None,
            repositories: None,
        }
    }
}

