/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiIssueChange : An issue change.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiIssueChange {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::ApiAccount>>,
    #[serde(rename = "issue", skip_serializing_if = "Option::is_none")]
    pub issue: Option<Box<models::ApiIssue>>,
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<serde_json::Value>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<serde_json::Value>,
}

impl ApiIssueChange {
    /// An issue change.
    pub fn new(r#type: String) -> ApiIssueChange {
        ApiIssueChange {
            r#type,
            links: None,
            name: None,
            created_on: None,
            user: None,
            issue: None,
            changes: None,
            message: None,
        }
    }
}

