/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiProjectDeployKey {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The deploy key value.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::ApiProject>>,
    /// The comment parsed from the deploy key (if present)
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// The user-defined label for the deploy key
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "added_on", skip_serializing_if = "Option::is_none")]
    pub added_on: Option<String>,
    #[serde(rename = "last_used", skip_serializing_if = "Option::is_none")]
    pub last_used: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::ApiAccount>>,
}

impl ApiProjectDeployKey {
    pub fn new(r#type: String) -> ApiProjectDeployKey {
        ApiProjectDeployKey {
            r#type,
            key: None,
            project: None,
            comment: None,
            label: None,
            added_on: None,
            last_used: None,
            links: None,
            created_by: None,
        }
    }
}

