/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiRef : A ref object, representing a branch or tag in a repository.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiRef {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    /// The name of the ref.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<models::ApiCommit>>,
}

impl ApiRef {
    /// A ref object, representing a branch or tag in a repository.
    pub fn new(r#type: String) -> ApiRef {
        ApiRef {
            r#type,
            links: None,
            name: None,
            target: None,
        }
    }
}

