/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPipelineRunnerVersion {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The currently installed version of the runner.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// The current recommended version of the runner.
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
}

impl ApiPipelineRunnerVersion {
    pub fn new(r#type: String) -> ApiPipelineRunnerVersion {
        ApiPipelineRunnerVersion {
            r#type,
            version: None,
            current: None,
        }
    }
}

