/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiAppUser {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<models::ApiAccountLinks>,
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<String>,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The user's Atlassian account ID.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The status of the account. Currently the only possible value is \"active\", but more values may be added in the future.
    #[serde(rename = "account_status", skip_serializing_if = "Option::is_none")]
    pub account_status: Option<String>,
    /// The kind of App User.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
}

impl ApiAppUser {
    pub fn new(r#type: String) -> ApiAppUser {
        ApiAppUser {
            r#type,
            links: None,
            created_on: None,
            display_name: None,
            uuid: None,
            account_id: None,
            account_status: None,
            kind: None,
        }
    }
}

