/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiHookEvent : An event, associated with a resource or subject type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiHookEvent {
    /// The event identifier.
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<Event>,
    /// The category this event belongs to.
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Summary of the webhook event type.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// More detailed description of the webhook event type.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ApiHookEvent {
    /// An event, associated with a resource or subject type.
    pub fn new() -> ApiHookEvent {
        ApiHookEvent {
            event: None,
            category: None,
            label: None,
            description: None,
        }
    }
}
/// The event identifier.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "issue:comment_created")]
    IssueColonCommentCreated,
    #[serde(rename = "issue:created")]
    IssueColonCreated,
    #[serde(rename = "issue:updated")]
    IssueColonUpdated,
    #[serde(rename = "project:updated")]
    ProjectColonUpdated,
    #[serde(rename = "pullrequest:approved")]
    PullrequestColonApproved,
    #[serde(rename = "pullrequest:changes_request_created")]
    PullrequestColonChangesRequestCreated,
    #[serde(rename = "pullrequest:changes_request_removed")]
    PullrequestColonChangesRequestRemoved,
    #[serde(rename = "pullrequest:comment_created")]
    PullrequestColonCommentCreated,
    #[serde(rename = "pullrequest:comment_deleted")]
    PullrequestColonCommentDeleted,
    #[serde(rename = "pullrequest:comment_reopened")]
    PullrequestColonCommentReopened,
    #[serde(rename = "pullrequest:comment_resolved")]
    PullrequestColonCommentResolved,
    #[serde(rename = "pullrequest:comment_updated")]
    PullrequestColonCommentUpdated,
    #[serde(rename = "pullrequest:created")]
    PullrequestColonCreated,
    #[serde(rename = "pullrequest:fulfilled")]
    PullrequestColonFulfilled,
    #[serde(rename = "pullrequest:push")]
    PullrequestColonPush,
    #[serde(rename = "pullrequest:rejected")]
    PullrequestColonRejected,
    #[serde(rename = "pullrequest:unapproved")]
    PullrequestColonUnapproved,
    #[serde(rename = "pullrequest:updated")]
    PullrequestColonUpdated,
    #[serde(rename = "repo:commit_comment_created")]
    RepoColonCommitCommentCreated,
    #[serde(rename = "repo:commit_status_created")]
    RepoColonCommitStatusCreated,
    #[serde(rename = "repo:commit_status_updated")]
    RepoColonCommitStatusUpdated,
    #[serde(rename = "repo:created")]
    RepoColonCreated,
    #[serde(rename = "repo:deleted")]
    RepoColonDeleted,
    #[serde(rename = "repo:fork")]
    RepoColonFork,
    #[serde(rename = "repo:imported")]
    RepoColonImported,
    #[serde(rename = "repo:push")]
    RepoColonPush,
    #[serde(rename = "repo:transfer")]
    RepoColonTransfer,
    #[serde(rename = "repo:updated")]
    RepoColonUpdated,
}

impl Default for Event {
    fn default() -> Event {
        Self::IssueColonCommentCreated
    }
}

