/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiWebhookSubscription {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The webhook's id
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The URL events get delivered to.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// A user-defined description of the webhook.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The type of entity. Set to either `repository` or `workspace` based on where the subscription is defined.
    #[serde(rename = "subject_type", skip_serializing_if = "Option::is_none")]
    pub subject_type: Option<SubjectType>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<models::ApiObject>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The events this webhook is subscribed to.
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<std::collections::HashSet<Events>>,
    /// Indicates whether or not the hook has an associated secret. It is not possible to see the hook's secret. This field is ignored during updates.
    #[serde(rename = "secret_set", skip_serializing_if = "Option::is_none")]
    pub secret_set: Option<bool>,
    /// The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null` or \"\" to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl ApiWebhookSubscription {
    pub fn new(r#type: String) -> ApiWebhookSubscription {
        ApiWebhookSubscription {
            r#type,
            uuid: None,
            url: None,
            description: None,
            subject_type: None,
            subject: None,
            active: None,
            created_at: None,
            events: None,
            secret_set: None,
            secret: None,
        }
    }
}
/// The type of entity. Set to either `repository` or `workspace` based on where the subscription is defined.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubjectType {
    #[serde(rename = "repository")]
    Repository,
    #[serde(rename = "workspace")]
    Workspace,
}

impl Default for SubjectType {
    fn default() -> SubjectType {
        Self::Repository
    }
}
/// The events this webhook is subscribed to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "issue:comment_created")]
    IssueColonCommentCreated,
    #[serde(rename = "issue:created")]
    IssueColonCreated,
    #[serde(rename = "issue:updated")]
    IssueColonUpdated,
    #[serde(rename = "pipeline:span_created")]
    PipelineColonSpanCreated,
    #[serde(rename = "project:updated")]
    ProjectColonUpdated,
    #[serde(rename = "pullrequest:approved")]
    PullrequestColonApproved,
    #[serde(rename = "pullrequest:changes_request_created")]
    PullrequestColonChangesRequestCreated,
    #[serde(rename = "pullrequest:changes_request_removed")]
    PullrequestColonChangesRequestRemoved,
    #[serde(rename = "pullrequest:comment_created")]
    PullrequestColonCommentCreated,
    #[serde(rename = "pullrequest:comment_deleted")]
    PullrequestColonCommentDeleted,
    #[serde(rename = "pullrequest:comment_reopened")]
    PullrequestColonCommentReopened,
    #[serde(rename = "pullrequest:comment_resolved")]
    PullrequestColonCommentResolved,
    #[serde(rename = "pullrequest:comment_updated")]
    PullrequestColonCommentUpdated,
    #[serde(rename = "pullrequest:created")]
    PullrequestColonCreated,
    #[serde(rename = "pullrequest:fulfilled")]
    PullrequestColonFulfilled,
    #[serde(rename = "pullrequest:push")]
    PullrequestColonPush,
    #[serde(rename = "pullrequest:rejected")]
    PullrequestColonRejected,
    #[serde(rename = "pullrequest:unapproved")]
    PullrequestColonUnapproved,
    #[serde(rename = "pullrequest:updated")]
    PullrequestColonUpdated,
    #[serde(rename = "repo:commit_comment_created")]
    RepoColonCommitCommentCreated,
    #[serde(rename = "repo:commit_status_created")]
    RepoColonCommitStatusCreated,
    #[serde(rename = "repo:commit_status_updated")]
    RepoColonCommitStatusUpdated,
    #[serde(rename = "repo:created")]
    RepoColonCreated,
    #[serde(rename = "repo:deleted")]
    RepoColonDeleted,
    #[serde(rename = "repo:fork")]
    RepoColonFork,
    #[serde(rename = "repo:imported")]
    RepoColonImported,
    #[serde(rename = "repo:push")]
    RepoColonPush,
    #[serde(rename = "repo:transfer")]
    RepoColonTransfer,
    #[serde(rename = "repo:updated")]
    RepoColonUpdated,
}

impl Default for Events {
    fn default() -> Events {
        Self::IssueColonCommentCreated
    }
}

