/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BitbucketAppsPermissionsSerializersProjectPermissionUpdateSchema {
    #[serde(rename = "permission")]
    pub permission: Permission,
}

impl BitbucketAppsPermissionsSerializersProjectPermissionUpdateSchema {
    pub fn new(permission: Permission) -> BitbucketAppsPermissionsSerializersProjectPermissionUpdateSchema {
        BitbucketAppsPermissionsSerializersProjectPermissionUpdateSchema {
            permission,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permission {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "create-repo")]
    CreateRepo,
    #[serde(rename = "admin")]
    Admin,
}

impl Default for Permission {
    fn default() -> Permission {
        Self::Read
    }
}

