/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<models::Account>>,
    #[serde(rename = "workspace", skip_serializing_if = "Option::is_none")]
    pub workspace: Option<Box<models::Workspace>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The \"sluggified\" version of the group's name. This contains only ASCII characters and can therefore be slightly different than the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The concatenation of the workspace's slug and the group's slug, separated with a colon (e.g. `acme:developers`) 
    #[serde(rename = "full_slug", skip_serializing_if = "Option::is_none")]
    pub full_slug: Option<String>,
}

impl Group {
    pub fn new(r#type: String) -> Group {
        Group {
            r#type,
            links: None,
            owner: None,
            workspace: None,
            name: None,
            slug: None,
            full_slug: None,
        }
    }
}

