/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineStepStateCompleted {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The name of pipeline step state (COMPLETED).
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::PipelineStepStateCompletedResult>>,
}

impl PipelineStepStateCompleted {
    pub fn new(r#type: String) -> PipelineStepStateCompleted {
        PipelineStepStateCompleted {
            r#type,
            name: None,
            result: None,
        }
    }
}
/// The name of pipeline step state (COMPLETED).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "COMPLETED")]
    Completed,
}

impl Default for Name {
    fn default() -> Name {
        Self::Completed
    }
}

