/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PipelineConfigurationSource : Information about the source of the pipeline configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineConfigurationSource {
    /// Identifier of the configuration source
    #[serde(rename = "source")]
    pub source: String,
    /// Link to the configuration source view or its immediate content
    #[serde(rename = "uri")]
    pub uri: String,
}

impl PipelineConfigurationSource {
    /// Information about the source of the pipeline configuration
    pub fn new(source: String, uri: String) -> PipelineConfigurationSource {
        PipelineConfigurationSource {
            source,
            uri,
        }
    }
}

