/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineSchedulePutRequestBody {
    #[serde(rename = "type")]
    pub r#type: String,
    /// Whether the schedule is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl PipelineSchedulePutRequestBody {
    pub fn new(r#type: String) -> PipelineSchedulePutRequestBody {
        PipelineSchedulePutRequestBody {
            r#type,
            enabled: None,
        }
    }
}

