/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineStepStateCompletedError {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The name of the result (ERROR)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::PipelineStepError>>,
}

impl PipelineStepStateCompletedError {
    pub fn new(r#type: String) -> PipelineStepStateCompletedError {
        PipelineStepStateCompletedError {
            r#type,
            name: None,
            error: None,
        }
    }
}
/// The name of the result (ERROR)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "ERROR")]
    Error,
}

impl Default for Name {
    fn default() -> Name {
        Self::Error
    }
}

