/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelinesPipelineLinks {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::PipelinesLinksSectionHref>>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Box<models::PipelinesLinksSectionHref>>,
}

impl PipelinesPipelineLinks {
    pub fn new(r#type: String) -> PipelinesPipelineLinks {
        PipelinesPipelineLinks {
            r#type,
            param_self: None,
            steps: None,
        }
    }
}

