/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pipeline {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The UUID identifying the pipeline.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The build number of the pipeline.
    #[serde(rename = "build_number", skip_serializing_if = "Option::is_none")]
    pub build_number: Option<i32>,
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<Box<models::Account>>,
    #[serde(rename = "repository", skip_serializing_if = "Option::is_none")]
    pub repository: Option<Box<models::Repository>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<models::PipelineTarget>>,
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Box<models::PipelineTrigger>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::PipelineState>>,
    /// The variables for the pipeline.
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Vec<models::PipelineVariable>>,
    /// The timestamp when the pipeline was created.
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<String>,
    /// The timestamp when the Pipeline was completed. This is not set if the pipeline is still in progress.
    #[serde(rename = "completed_on", skip_serializing_if = "Option::is_none")]
    pub completed_on: Option<String>,
    /// The number of build seconds used by this pipeline.
    #[serde(rename = "build_seconds_used", skip_serializing_if = "Option::is_none")]
    pub build_seconds_used: Option<i32>,
    /// An ordered list of sources of the pipeline configuration
    #[serde(rename = "configuration_sources", skip_serializing_if = "Option::is_none")]
    pub configuration_sources: Option<Vec<models::PipelineConfigurationSource>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::PipelinesPipelineLinks>>,
}

impl Pipeline {
    pub fn new(r#type: String) -> Pipeline {
        Pipeline {
            r#type,
            uuid: None,
            build_number: None,
            creator: None,
            repository: None,
            target: None,
            trigger: None,
            state: None,
            variables: None,
            created_on: None,
            completed_on: None,
            build_seconds_used: None,
            configuration_sources: None,
            links: None,
        }
    }
}

