/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PipelineImage : The definition of a Docker image that can be used for a Bitbucket Pipelines step execution context.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineImage {
    /// The name of the image. If the image is hosted on DockerHub the short name can be used, otherwise the fully qualified name is required here.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The username needed to authenticate with the Docker registry. Only required when using a private Docker image.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// The password needed to authenticate with the Docker registry. Only required when using a private Docker image.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// The email needed to authenticate with the Docker registry. Only required when using a private Docker image.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl PipelineImage {
    /// The definition of a Docker image that can be used for a Bitbucket Pipelines step execution context.
    pub fn new() -> PipelineImage {
        PipelineImage {
            name: None,
            username: None,
            password: None,
            email: None,
        }
    }
}

