/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineRefTarget {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The type of reference (branch/tag).
    #[serde(rename = "ref_type", skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<RefType>,
    /// The name of the reference.
    #[serde(rename = "ref_name", skip_serializing_if = "Option::is_none")]
    pub ref_name: Option<String>,
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::Commit>>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<models::PipelineSelector>>,
}

impl PipelineRefTarget {
    pub fn new(r#type: String) -> PipelineRefTarget {
        PipelineRefTarget {
            r#type,
            ref_type: None,
            ref_name: None,
            commit: None,
            selector: None,
        }
    }
}
/// The type of reference (branch/tag).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefType {
    #[serde(rename = "branch")]
    Branch,
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "named_branch")]
    NamedBranch,
    #[serde(rename = "bookmark")]
    Bookmark,
}

impl Default for RefType {
    fn default() -> RefType {
        Self::Branch
    }
}

