/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineKnownHost {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The UUID identifying the known host.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The hostname of the known host.
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "public_key", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Box<models::PipelineSshPublicKey>>,
}

impl PipelineKnownHost {
    pub fn new(r#type: String) -> PipelineKnownHost {
        PipelineKnownHost {
            r#type,
            uuid: None,
            hostname: None,
            public_key: None,
        }
    }
}

