/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PullrequestTaskCreate : A pullrequest task create
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullrequestTaskCreate {
    /// task raw content
    #[serde(rename = "content")]
    pub content: serde_json::Value,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Box<models::Comment>>,
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<bool>,
}

impl PullrequestTaskCreate {
    /// A pullrequest task create
    pub fn new(content: serde_json::Value) -> PullrequestTaskCreate {
        PullrequestTaskCreate {
            content,
            comment: None,
            pending: None,
        }
    }
}

