/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullrequestTask {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "created_on")]
    pub created_on: String,
    #[serde(rename = "updated_on")]
    pub updated_on: String,
    #[serde(rename = "state")]
    pub state: State,
    #[serde(rename = "content")]
    pub content: serde_json::Value,
    #[serde(rename = "creator")]
    pub creator: Box<models::Account>,
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<bool>,
    /// The ISO8601 timestamp for when the task was resolved.
    #[serde(rename = "resolved_on", skip_serializing_if = "Option::is_none")]
    pub resolved_on: Option<String>,
    #[serde(rename = "resolved_by", skip_serializing_if = "Option::is_none")]
    pub resolved_by: Option<Box<models::Account>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
}

impl PullrequestTask {
    pub fn new(created_on: String, updated_on: String, state: State, content: serde_json::Value, creator: models::Account) -> PullrequestTask {
        PullrequestTask {
            id: None,
            created_on,
            updated_on,
            state,
            content,
            creator: Box::new(creator),
            pending: None,
            resolved_on: None,
            resolved_by: None,
            links: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "RESOLVED")]
    Resolved,
    #[serde(rename = "UNRESOLVED")]
    Unresolved,
}

impl Default for State {
    fn default() -> State {
        Self::Resolved
    }
}

