/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportAnnotation {
    #[serde(rename = "type")]
    pub r#type: String,
    /// ID of the annotation provided by the annotation creator. It can be used to identify the annotation as an alternative to it's generated uuid. It is not used by Bitbucket, but only by the annotation creator for updating or deleting this specific annotation. Needs to be unique.
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// The UUID that can be used to identify the annotation.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The type of the report.
    #[serde(rename = "annotation_type", skip_serializing_if = "Option::is_none")]
    pub annotation_type: Option<AnnotationType>,
    /// The path of the file on which this annotation should be placed. This is the path of the file relative to the git repository. If no path is provided, then it will appear in the overview modal on all pull requests where the tip of the branch is the given commit, regardless of which files were modified.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// The line number that the annotation should belong to. If no line number is provided, then it will default to 0 and in a pull request it will appear at the top of the file specified by the path field.
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<u32>,
    /// The message to display to users.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// The details to show to users when clicking on the annotation.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// The state of the report. May be set to PENDING and later updated.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Result>,
    /// The severity of the annotation.
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<Severity>,
    /// A URL linking to the annotation in an external tool.
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    /// The timestamp when the report was created.
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<String>,
    /// The timestamp when the report was updated.
    #[serde(rename = "updated_on", skip_serializing_if = "Option::is_none")]
    pub updated_on: Option<String>,
}

impl ReportAnnotation {
    pub fn new(r#type: String) -> ReportAnnotation {
        ReportAnnotation {
            r#type,
            external_id: None,
            uuid: None,
            annotation_type: None,
            path: None,
            line: None,
            summary: None,
            details: None,
            result: None,
            severity: None,
            link: None,
            created_on: None,
            updated_on: None,
        }
    }
}
/// The type of the report.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AnnotationType {
    #[serde(rename = "VULNERABILITY")]
    Vulnerability,
    #[serde(rename = "CODE_SMELL")]
    CodeSmell,
    #[serde(rename = "BUG")]
    Bug,
}

impl Default for AnnotationType {
    fn default() -> AnnotationType {
        Self::Vulnerability
    }
}
/// The state of the report. May be set to PENDING and later updated.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "PASSED")]
    Passed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "SKIPPED")]
    Skipped,
    #[serde(rename = "IGNORED")]
    Ignored,
}

impl Default for Result {
    fn default() -> Result {
        Self::Passed
    }
}
/// The severity of the annotation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Severity {
    #[serde(rename = "CRITICAL")]
    Critical,
    #[serde(rename = "HIGH")]
    High,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "LOW")]
    Low,
}

impl Default for Severity {
    fn default() -> Severity {
        Self::Critical
    }
}

