/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Repository {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    /// The repository's immutable id. This can be used as a substitute for the slug segment in URLs. Doing this guarantees your URLs will survive renaming of the repository by its owner, or even transfer of the repository to a different user.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The concatenation of the repository owner's username and the slugified name, e.g. \"evzijst/interruptingcow\". This is the same string used in Bitbucket URLs.
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "is_private", skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::Repository>>,
    #[serde(rename = "scm", skip_serializing_if = "Option::is_none")]
    pub scm: Option<Scm>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<models::Account>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "created_on", skip_serializing_if = "Option::is_none")]
    pub created_on: Option<String>,
    #[serde(rename = "updated_on", skip_serializing_if = "Option::is_none")]
    pub updated_on: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    ///  The issue tracker for this repository is enabled. Issue Tracker features are not supported for repositories in workspaces administered through admin.atlassian.com. 
    #[serde(rename = "has_issues", skip_serializing_if = "Option::is_none")]
    pub has_issues: Option<bool>,
    ///  The wiki for this repository is enabled. Wiki features are not supported for repositories in workspaces administered through admin.atlassian.com. 
    #[serde(rename = "has_wiki", skip_serializing_if = "Option::is_none")]
    pub has_wiki: Option<bool>,
    ///  Controls the rules for forking this repository.  * **allow_forks**: unrestricted forking * **no_public_forks**: restrict forking to private forks (forks cannot   be made public later) * **no_forks**: deny all forking 
    #[serde(rename = "fork_policy", skip_serializing_if = "Option::is_none")]
    pub fork_policy: Option<ForkPolicy>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "mainbranch", skip_serializing_if = "Option::is_none")]
    pub mainbranch: Option<Box<models::Branch>>,
}

impl Repository {
    pub fn new(r#type: String) -> Repository {
        Repository {
            r#type,
            links: None,
            uuid: None,
            full_name: None,
            is_private: None,
            parent: None,
            scm: None,
            owner: None,
            name: None,
            description: None,
            created_on: None,
            updated_on: None,
            size: None,
            language: None,
            has_issues: None,
            has_wiki: None,
            fork_policy: None,
            project: None,
            mainbranch: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scm {
    #[serde(rename = "git")]
    Git,
}

impl Default for Scm {
    fn default() -> Scm {
        Self::Git
    }
}
///  Controls the rules for forking this repository.  * **allow_forks**: unrestricted forking * **no_public_forks**: restrict forking to private forks (forks cannot   be made public later) * **no_forks**: deny all forking 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ForkPolicy {
    #[serde(rename = "allow_forks")]
    AllowForks,
    #[serde(rename = "no_public_forks")]
    NoPublicForks,
    #[serde(rename = "no_forks")]
    NoForks,
}

impl Default for ForkPolicy {
    fn default() -> ForkPolicy {
        Self::AllowForks
    }
}

