/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubjectTypes : The mapping of resource/subject types pointing to their individual event types.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectTypes {
    #[serde(rename = "repository", skip_serializing_if = "Option::is_none")]
    pub repository: Option<serde_json::Value>,
    #[serde(rename = "workspace", skip_serializing_if = "Option::is_none")]
    pub workspace: Option<serde_json::Value>,
}

impl SubjectTypes {
    /// The mapping of resource/subject types pointing to their individual event types.
    pub fn new() -> SubjectTypes {
        SubjectTypes {
            repository: None,
            workspace: None,
        }
    }
}

