/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@bitbucket.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceAccess {
    #[serde(rename = "type")]
    pub r#type: String,
    /// The permission level the user has for the workspace. \"True\" if the user is an administrator, otherwise \"False\".
    #[serde(rename = "administrator", skip_serializing_if = "Option::is_none")]
    pub administrator: Option<String>,
    #[serde(rename = "workspace", skip_serializing_if = "Option::is_none")]
    pub workspace: Option<Box<models::WorkspaceBase>>,
}

impl WorkspaceAccess {
    pub fn new(r#type: String) -> WorkspaceAccess {
        WorkspaceAccess {
            r#type,
            administrator: None,
            workspace: None,
        }
    }
}

